### ISSUE TITLE
Installation failure -- update_depot_tools_toggle.py: no such file or directory

### ISSUE THREAD

**Issue by plainwu** [rubyjs/libv8#308] opened 2020-11-20 07:23 UTC
```
❯ gem install libv8 -v '8.4.255.0'
Building native extensions. This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8
/Users/plainwu/.rbenv/versions/2.6.6/bin/ruby -I /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/2.6.0 -r ./siteconf20201120-94549-1ltuysc.rb extconf.rb
creating Makefile
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor/_gclient_v8_lyqfjv7m' in '/Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor'
Cloning into '/Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor/_gclient_v8_lyqfjv7m'...
remote: Sending approximately 729.94 MiB ...
remote: Counting objects: 7663, done
remote: Finding sources: 100% (3/3)
remote: Total 800974 (delta 648651), reused 800974 (delta 648651)
Receiving objects: 100% (800974/800974), 729.93 MiB | 10.74 MiB/s, done.
Resolving deltas: 100% (648651/648651), done.
[0:02:07] Still working on:
[0:02:07]   v8
________ running 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor'
/Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor/depot_tools/.cipd_bin/vpython: could not resolve options: failed to resolve Python script: stat /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor/third_party/depot_tools/update_depot_tools_toggle.py: no such file or directory
Error: Command 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' returned non-zero exit status 1 in /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/vendor
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Subprocess failed with return code 2.
/Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:81:in `chdir'
	from /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:81:in `setup_build_deps!'
	from /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8/builder.rb:40:in `build_libv8!'
	from /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/libv8-8.4.255.0 for inspection.
Results logged to /Users/plainwu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/libv8-8.4.255.0/gem_make.out
```

I can find update_depot_tools_toggle.py in libv8-8.4.255.0/vendor/depot_tools but not libv8-8.4.255.0/vendor/third_party/depot_tools
vendor/**third_party** folder looks like removed by someone.

**Comment by sarthology** [comment] 2020-11-20 09:52
+1

**Comment by lloeki** [comment] 2020-11-20 10:58
`x86_64-darwin-20`, so dupe of #305

**Comment by plainwu** [comment] 2020-11-21 02:59
Thanks to @lloeki , it works!

**Closed** 2020-11-21 02:59 UTC
